### ISSUE TITLE
Any way to avoid Template Haskell during cross-compilation?

### ISSUE THREAD

**Issue by livmackintosh** [jgm/unicode-collation#10]
This isn't a bug but rather a limitation in my own knowledge 😄: Is there any for me to avoid using Template Haskell when deriving the root collation table? I'm cross-comping my project that is targeting aarch64-linux-android but naturally this doesn't work. I don't mind if I created a fork that only works with my target platform but it's over my head. 🤯.

**Comment by jgm** [comment]
I haven't tried this, but apparently you can use `-ddump-splices` to see the generated code:
```
ghc -XTemplateHaskell -ddump-splices Prog.hs 2> Prog.dump-splices
```
so maybe you can do this and paste in the generated code?
It looks like maybe the way this works changes between ghc versions, see the discussion here:
https://stackoverflow.com/questions/15851060/ghc-ddump-splices-option-template-haskell

**Comment by jgm** [comment]
Sorry, looks like on current ghc you use `-ddump-splices` with `-ddump-to-file` instead of redirecting stderr.
