### ISSUE TITLE
Allow base 4.17

### ISSUE THREAD

**Issue by Merivuokko** [jgm/unicode-collation#12]
unicode-collation builds fine with base 4.17.

The dependency bound for base could be relaxed.

**Comment by byorgey** [comment]
@jgm No rush, but just wanted to check what the plans are for releasing 0.1.3.3 to Hackage, since it's currently blocking `BlogLiterately` from building on GHC 9.4.  No worries if you just haven't got around to it yet or if there's something else holding it up.

**Comment by jgm** [comment]
Thanks for the reminder. I think I was just waiting for CI to finish...and then lost track.

**Comment by jgm** [comment]
Released!
