### ISSUE TITLE
Unexpected results for "de-u-co-phonebk"

### ISSUE THREAD

**Issue by njbart** [jgm/unicode-collation#2]
I have looked at just a few languages so far, especially those that deviate in some way from the root collation order (based on the info from https://en.wikipedia.org/wiki/Alphabetical_order#Language-specific_conventions).

For Danish, Swedish, Spanish and French the output from `unicode-collate` looks good for now, including the expected differences between, e.g., `sv` vs. `sv-u-co-reformed`, `es` vs. `es-u-co-trad` and `fr` vs. `fr-u-kb`.

For German, the root collation (`de`) looks ok, but there’s also a "phonebook" order which, according to the Wikipedia entry, should be "Udet, Übelacker, Uell, Ülle, Ueve, Üxküll, Uffenbach" (treating umlauts "ä", "ö", "ü" like the letter combinations "ae", "oe", "ue"). https://icu4c-demos.unicode.org/icu-bin/collation.html, using `de-u-co-phonebk`, generates the same order.

But `unicode-collate de-u-co-phonebk`, using the same list of names, generates the following instead:

Übelacker
Udet
Uell
Ueve
Uffenbach
Ülle
Üxküll

... which does not seem to differ from the `de` collation at all.

**Comment by jgm** [comment]
Here's what the collation data file has:
``` xml
                <collation type="phonebook">
                        <cr><![CDATA[
                                &AE<<ä<<<Ä
                                &OE<<ö<<<Ö
                                &UE<<ü<<<Ü
                        ]]></cr>
                </collation>
```
Note that contractions are case-sensitive, so Ue is different from UE (unless I'm mistaken about the rules).

https://unicode.org/reports/tr35/tr35-collation.html#Rules
"The collation syntax is case-sensitive."
It's possible that the requirement "Weights must be allocated in accordance with the UCA well-formedness conditions." is relevant here; I have to look into that, but the documentation is not always that easy...

**Comment by jgm** [comment]
Note:
```
> sortKey "de-u-co-standard" "Ü"
SortKey [0x2217,0x0000,0x0020,0x002B,0x0000,0x0008,0x0002,0x0000,0xFFFF,0xFFFF]
> sortKey "de-u-co-phonebk" "Ü"
SortKey [0x2217,0x0000,0x0021,0x0000,0x0009,0x0000,0xFFFF]
```
So there is a difference here.  But
```
> sortKey "de-u-co-phonebk" "Ud"
SortKey [0x2217,0x1FEB,0x0000,0x0020,0x0020,0x0000,0x0008,0x0002,0x0000,0xFFFF,0xFFFF]
> sortKey "de-u-co-phonebk" "Ud" == sortKey "de-u-co-standard" "Ud"
True
```

**Comment by jgm** [comment]
The tailoring phonebk:
``` haskell
,Tailoring {unTailoring =
  [After L2 (TargetText "AE") (TargetText "\228"),
   After L3 (TargetText "\228") (TargetText "\196"),
   After L2 (TargetText "OE") (TargetText "\246"),
   After L3 (TargetText "\246") (TargetText "\214"),
   After L2 (TargetText "UE") (TargetText "\252"),
   After L3 (TargetText "\252") (TargetText "\220")]})
```

**Comment by jgm** [comment]
So, I don't really understand this.  The tailoring specifies a difference in sorting at level 2 and level 3 (`<<`, `<<<`), but with Übelacker and Udet you get a difference at level 1, which should take priority.  So if I understand properly, there shouldn't be a difference in how standard and phonebk sort these strings.

**Comment by jgm** [comment]
Oh, I think I must have misinterpreted `<<` and `<<<`.
I'm having them set JUST the level 2 and level 3 weights, but it must be the intention that the primary weights be set to equal as well...

**Comment by jgm** [comment]
More data:
```
> map ord $ T.unpack $ normalize NFD "Ud"
[85,100]
> map ord $ T.unpack $ normalize NFD "Üb"
[85,776,98]
> getCollationElements (optCollation $ collatorOptions "de-u-co-phonebk") [85,100]
[CollationElement False 0x2217 0x0020 0x0008 0xFFFF, CollationElement False 0x1FEB 0x0020 0x0002 0xFFFF]
> getCollationElements (optCollation $ collatorOptions "de-u-co-phonebk") [85,776,98]
[CollationElement False 0x2217 0x0021 0x0009 0xFFFF, CollationElement False 0x1FBC 0x0020 0x0002 0xFFFF]
```

**Comment by jgm** [comment]
Clearly the tailoring part of my code is wrong when the "target" is a contraction.

**Comment by jgm** [comment]
```
> map ord $ T.unpack $ normalize NFD "UE"
[85,69]
> map ord $ T.unpack $ normalize NFD "ü"
[117,776]
> getCollationElements (optCollation $ collatorOptions "de-u-co-phonebk") [85,69] -- UE
[CollationElement False 0x2217 0x0020 0x0008 0xFFFF,
 CollationElement False 0x2007 0x0020 0x0008 0xFFFF]
> getCollationElements (optCollation $ collatorOptions "de-u-co-phonebk") [117,776] - ü
[CollationElement False 0x2217 0x0021 0x0008 0xFFFF]
> getCollationElements (optCollation $ collatorOptions "de-u-co-standard") [117,776]
[CollationElement False 0x2217 0x0020 0x0002 0xFFFF,
 CollationElement False 0x0000 0x002B 0x0002 0xFFFF]
```

**Comment by jgm** [comment]
Comparing perl's library
https://metacpan.org/source/SADAHIRO/Unicode-Collate-1.29/Collate%2FLocale%2Fde_phone.pl
they have for LATIN SMALL LETTER U WITH DIAERESIS
```
 [.2217.0021.0002][.2007.0021.0002]
```
so this alters the collation in "standard" by leaving the first element the same and  changing the second element from 0000.002B.0002 to 2007.0021.0002.  First element is 'u'.
That second element is picked to be greater than  'e' which is 1FEB.0020.0002; note that it is greater in both the primary and secondary part.

An easy way out would be to use the locale tables in the perl module, which are based on DUCET allkeys.txt and would avoid the need to include allkeys_CLDR.txt in the source as well.  (Then we could dispense with the code for parsing locale files, and the locale files themselves. We'd lose the ability to do custom tailorings though.)

**Comment by jgm** [comment]
OK, I think I have this working now.

**Comment by jgm** [comment]
More testing would be helpful, though!
