### ISSUE TITLE
Could you please expose internal module?

### ISSUE THREAD

**Issue by winterland1989** [jgm/unicode-collation#4]
As the author of [Z-Data](https://hackage.haskell.org/package/Z-Data), we'd like to add support to unicode-collation, but our `Text` type use UTF-8 encoding, which is different to `text` 's one. So could you please add API for creating sort keys from `[Int]` directly? I assumed this can be done via exposing some internal modules.

**Comment by jgm** [comment]
Do you already have a mechanism for normalizing your UTF-8 encoded texts into NFD form?  That is a required step of the algorithm.  If so, I can expose something like
``` hs
normalizedCodePointsToSortKey :: Collation -> VariableWeighting -> [Int] -> SortKey
normalizedCodePointsToSortKey collation weighting =
    mkSortKey opts                                             
  . handleVariable weighting
  . getCollationElements collation 
```
But if you don't have the normalization piece yet, this won't do any good.  unicode-transforms is limited to Text.

Note: I've requested that unicode-transforms expose an interface for incremental normalization:
https://github.com/composewell/unicode-transforms/issues/60
If, on top of that, they also exposed an interface that factored out the `stream` step (Text -> Stream Char), then you'd have something you could use directly.  You might request that.

**Comment by winterland1989** [comment]
Yes, it’s already [there](https://hackage.haskell.org/package/Z-Data-0.8.0.0/docs/Z-Data-Text.html#g:15)

**Comment by jgm** [comment]
Would the signature noted above be the right kind of thing for you to use?

**Comment by jgm** [comment]
Let me know if this commit gives you what you need.
I'll wait for your comment before releasing anything.

**Comment by winterland1989** [comment]
Thanks, it definitely works.

**Comment by jgm** [comment]
My latest version gives you something a bit different, but hopefully still workable:
```hs
    -- | Compare two strings of any type that can be unpacked
    -- lazily into a list of 'Char's.
  , collateWithUnpacker   :: forall a. Eq a => (a -> [Char]) -> a -> a -> Ordering
```

**Comment by jgm** [comment]
Also note that in the latest version (0.1.3), you `collateWithUnpacker` does *not* assume that the string is normalized.  It will do the normalization for you, unless you explicitly turn it off with `setNormalization`.

**Comment by winterland1989** [comment]
Yes, I see, that's a better API indeed.
