### ISSUE TITLE
What was wrong with the Tibetan character example?

### ISSUE THREAD

**Issue by despresc** [jgm/unicode-collation#5]
In the TODO you mention that `0F81` becomes `0F71 0F80` under NFD, but that's the expected canonical decomposition of that character, isn't it? So I'm curious what the failing test was.

**Comment by jgm** [comment]
Here are the test failures:
```
    Conformance tests Shifted test/uca-collation-test/CollationTest_SHIFTED_SHORT.txt:            FAIL (0.41s)
      test/unit.hs:164:
      [line 113601] 0FB2 0334 0F81 <= 0F77 0021
        Calculated sort keys:
        [0FB2 0334 0F81] [3331 | 0020 004A | 0002 0002 | FFFF FFFF]
        [0F77 0021] [3331 | 0020 | 0002 | FFFF 0267]
      [line 113641] 0FB3 0F71 0334 0F80 <= 0F79 0021
        Calculated sort keys:
        [0FB3 0F71 0334 0F80] [3333 | 0020 004A | 0002 0002 | FFFF FFFF]
        [0F79 0021] [3333 | 0020 | 0002 | FFFF 0267]
```
I think the reason for that comment was that the tables contain a line for 0F81, which surprised me since they normally expect NFD input.

**Comment by jgm** [comment]
Conformance tests have
```
0FB2 0334 0F81; # (ྲ̴) TIBETAN SUBJOINED LETTER RA, COMBINING TILDE OVERLAY       [3330 3329 | 0020 004A 0020 | 0002 0002 0002 | FFFF FFFF FFFF |]   
0F77 0021;      # (ཷ) TIBETAN VOWEL SIGN VOCALIC RR      [3331 | 0020 | 0002 | FFFF 0267 |]  
```
```
0FB3 0F71 0334 0F80;	# (ླ̴ཱ) TIBETAN SUBJOINED LETTER LA, TIBETAN VOWEL SIGN AA, COMBINING TILDE OVERLAY	[3332 3329 | 0020 004A 0020 | 0002 0002 0002 | FFFF FFFF FFFF |]
0F79 0021;	# (ཹ) TIBETAN VOWEL SIGN VOCALIC LL	[3333 | 0020 | 0002 | FFFF 0267 |]
```

**Comment by jgm** [comment]
```
% unicode-collate --verbose --hex bo-u-ka-shifted-true
Options:
  Tailoring:          ROOT
  Variable weighting: NonIgnorable
  French accents:     False
  Upper before lower: False
  Normalize:          True
0FB2 0334 0F81
0F77 0021
^D
0F77 0021; # (ཷ!) [3331 0267 | 0020 0020 | 0002 0002]
0FB2 0334 0F71 0F80; # (ྲ̴ཱྀ) [3331 | 0020 004A | 0002 0002]
```
```
% unicode-collate --verbose --hex bo-u-ka-shifted-true
Options:
  Tailoring:          ROOT
  Variable weighting: NonIgnorable
  French accents:     False
  Upper before lower: False
  Normalize:          True
0FB3 0F71 0334 0F80
0F79 0021
^D
0F79 0021; # (ཹ!) [3333 0267 | 0020 0020 | 0002 0002]
0FB3 0334 0F71 0F80; # (ླ̴ཱྀ) [3333 | 0020 004A | 0002 0002]
```

**Comment by despresc** [comment]
Thanks. It may not be a coincidence that both tests (after normalization) involve the [only two contraction mappings](https://www.unicode.org/reports/tr10/#Well_Formed_DUCET) that are mising from DUCET.

**Comment by despresc** [comment]
I'm not totally sure what's causing the problem in the implementation here, but it seems this is going wrong:

The sequence `0FB3 0F71 0F80` is present in the collation table, but `0FB3 0F71` is not. If it *were*, then the algorithm would effectively reorder the sequence `0FB3 0334 0F71 0F80` to

```
0FB3 0F71 0F80 | 0334
```

since it would be able to detect the discontiguous match. This would result in the element array and sort key

```
[.3331.0020.0002],[.0000.004A.0002]
3331 | 0020 004A | 0002 0002
```

That sort key is what this library is producing, according to the test output you posted. However, since the `0FB3 0F71` entry is not present in the table, the algorithm should recognize the sequence as

```
0FB3 |  0334 | 0F71 0F80
```

and so the correct element array and sort key are actually

```
[.3313.0020.0002],[.0000.004A.0002],[.332D.0020.0002]
3313 332D | 0020 004A 0020 | 0002 0002 0002

```

**Comment by jgm** [comment]
Aha, so this has to do with
https://unicode.org/reports/tr10/#Well_Formed_DUCET
We could try adding all ten contractions:
```
0FB2 0F71 ; CE(0FB2) CE(0F71)
0FB3 0F71 ; CE(0FB3) CE(0F71)
0FB2 0F71 0F72 ; CE(0FB2) CE(0F71 0F72)
0FB2 0F73      ; CE(0FB2) CE(0F71 0F72)
0FB2 0F71 0F74 ; CE(0FB2) CE(0F71 0F74)
0FB2 0F75      ; CE(0FB2) CE(0F71 0F74)
0FB3 0F71 0F72 ; CE(0FB3) CE(0F71 0F72)
0FB3 0F73      ; CE(0FB3) CE(0F71 0F72)
0FB3 0F71 0F74 ; CE(0FB3) CE(0F71 0F74)
0FB3 0F75      ; CE(0FB3) CE(0F71 0F74)
```
But maybe there's an algorithmic solution that would not require changing the DUCET table?

**Comment by jgm** [comment]
Another alternative would be to change getCollationElements so that it looks for discontiguous matches after even partial matches on contractions.  That should solve this problem but maybe it would create other problems.  It would require some changes in matchLongestPrefix.

**Comment by despresc** [comment]
Adding in the ten seems a little brittle. The standard implies it would fix the problem, but I think it would have to be reviewed after every UCA release to make sure that the additions are still correct. Maybe that's okay. I'm not sure how likely it is that the situation will change between releases.

It seems like `getCollationElements` searches all the possible permutations of the unblocked non-starters, which lets it match `0FB3 0F71 0F80` when it shouldn't. So I would say the problem is that that function looks for discontiguous matches a little too eagerly, if anything.

If `getCollationElements` were modified to be a direct translation of the S.2.1.1-S.2.1.3 part of the algorithm then `matchLongestPrefix` shouldn't need to be changed, assuming that it does what [S2.1](https://www.unicode.org/reports/tr10/#S2.1) says to do.

**Comment by jgm** [comment]
Ah, thanks, I see the issue now!  The algorithm says to try the unblocked nonstarters one at a time.  I short-circuited that by considering all the permutations, which allows me to match (initial, x, y) even though (initial, x) by itself isn't a match.

**Comment by jgm** [comment]
Do you want to submit a PR to fix this?

**Comment by despresc** [comment]
Sure, I can.
